const gougeField = [
  [
    {
      id: 1,
      shipId: null,
      type: 'cell',
      defaultType: 'cell',
      value: null,
      coords: { x: 0, y: 0 },
    },
    {
      id: 2,
      shipId: null,
      type: 'cell',
      defaultType: 'cell',
      value: 'a',
      coords: { x: 1, y: 0 },
    },
    {
      id: 3,
      shipId: null,
      type: 'cell',
      defaultType: 'cell',
      value: 'b',
      coords: { x: 2, y: 0 },
    },
    {
      id: 4,
      shipId: null,
      type: 'cell',
      defaultType: 'cell',
      value: 'c',
      coords: { x: 3, y: 0 },
    },
  ],
  [
    {
      id: 101,
      shipId: null,
      type: 'cell',
      defaultType: 'cell',
      value: 1,
      coords: { x: 0, y: 1 },
    },
    {
      id: 102,
      shipId: null,
      type: 'cell-top-left',
      defaultType: 'cell-top-left',
      value: null,
      coords: { x: 1, y: 1 },
    },
    {
      id: 103,
      shipId: null,
      type: 'cell-top',
      defaultType: 'cell-top',
      value: null,
      coords: { x: 2, y: 1 },
    },
    {
      id: 104,
      shipId: null,
      type: 'cell-top-right',
      defaultType: 'cell-top-right',
      value: null,
      coords: { x: 3, y: 1 },
    },
  ],
  [
    {
      id: 201,
      shipId: null,
      type: 'cell',
      defaultType: 'cell',
      value: 2,
      coords: { x: 0, y: 2 },
    },
    {
      id: 202,
      shipId: null,
      type: 'cell-left',
      defaultType: 'cell-left',
      value: null,
      coords: { x: 1, y: 2 },
    },
    {
      id: 203,
      shipId: null,
      type: 'cell-inside',
      defaultType: 'cell-inside',
      value: null,
      coords: { x: 2, y: 2 },
    },
    {
      id: 204,
      shipId: null,
      type: 'cell-right',
      defaultType: 'cell-right',
      value: null,
      coords: { x: 3, y: 2 },
    },
  ],
  [
    {
      id: 301,
      shipId: null,
      type: 'cell',
      defaultType: 'cell',
      value: 3,
      coords: { x: 0, y: 3 },
    },
    {
      id: 302,
      shipId: null,
      type: 'cell-bottom-left',
      defaultType: 'cell-bottom-left',
      value: null,
      coords: { x: 1, y: 3 },
    },
    {
      id: 303,
      shipId: null,
      type: 'cell-bottom',
      defaultType: 'cell-bottom',
      value: null,
      coords: { x: 2, y: 3 },
    },
    {
      id: 304,
      shipId: null,
      type: 'cell-bottom-right',
      defaultType: 'cell-bottom-right',
      value: null,
      coords: { x: 3, y: 3 },
    },
  ],
];

export default gougeField;
